

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * # Safety
 *
 * TODO something more meaningful here
 */
void execute_tally_vm(const uint8_t *wasm_bytes,
                      uintptr_t wasm_bytes_len,
                      const char *const *args_ptr,
                      uintptr_t args_count,
                      const char *const *env_keys_ptr,
                      const char *const *env_values_ptr,
                      uintptr_t env_count);
